inherit_from: ../.rubocop.yml

# General note about rubocop.
# It does NOT allow to silence a specific rule violation.
# For that reason I sometimes have to disable a whole cop where
# I just tried to whitelist a specific occurence.


AllCops:
  Includes:
    - '../**/*.rake'
    - 'Gemfile'
    - 'Gemfile.triage'
    - 'ducktrap.gemspec'

# Avoid parameter lists longer than five parameters.
ParameterLists:
  Max: 3
  CountKeywordArgs: true

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 3

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    collect:  'map'
    inject:   'reduce'
    find:     'detect'
    find_all: 'select'

MethodLength:
  CountComments: false
  Max: 10

RegexpLiteral: # I do not agree %r(\A) is more readable than /\A/
  Enabled: false

Eval:
  Enabled: false # Mutant must use Kernel#eval to inject mutated source

# Limit line length
LineLength:
  Max: 79

# Disable documentation checking until a class needs to be documented once
Documentation:
  Enabled: false

# Do not favor modifier if/unless usage when you have a single-line body
IfUnlessModifier:
  Enabled: false

# Allow case equality operator (in limited use within the specs)
CaseEquality:
  Enabled: false

# Constants do not always have to use SCREAMING_SNAKE_CASE
ConstantName:
  Enabled: false

# Not all trivial readers/writers can be defined with attr_* methods
TrivialAccessors:
  Enabled: false

# And also have a differend opinion here
AndOr:
  Enabled: false

# I like my raise
SignalException:
  Enabled: false

# I need to chain optparse builder, else it is more ugly
MultilineBlockChain:
  Enabled: false

ClassLength:
  Max: 119

# I align private keywords with class body
IndentationWidth:
  Enabled: false

# I like to have an empty line before closing the currently opened body
EmptyLinesAroundBody:
  Enabled: false

# I like my style more
AccessModifierIndentation:
  Enabled: false
